conditioning:
  method: dmps
  params:
    scale: 1.75

data:
  name: mri # choices: mri, ffhq, bedroom, cat, celeba-hq
  root: ./data/mri_256_GroundTruth/ # address to put the associated images

measurement:
  operator:
    name: deblur
    type: uniform
    kernel_size: 9
    intensity: 3.0
  
  noise: 
    name: gaussian
    sigma: 0.05
