# Defaults for image training.

image_size: 256
#num_channels: 256  # 256x256_diffusion_uncond.pt
#num_res_blocks: 2  # 256x256_diffusion_uncond.pt
num_channels: 128  # model0x0000.pt
num_res_blocks: 3  # model0x0000.pt
channel_mult: ""
learn_sigma: True
class_cond: False
use_checkpoint: False
attention_resolutions: '32,16,8'
num_heads: 4
num_head_channels: 64
num_heads_upsample: -1
use_scale_shift_norm: True
dropout: 0.1
resblock_updown: True
use_fp16: True # if GPU Then True else False
use_new_attention_order: False

# download the checkpoint and put it under /models/
#model_path: models/256x256_diffusion_uncond.pt
model_path: models/model080000.pt
